= People's Liberation Training Committee
:toc: auto

== Purpose
In an age of collapsing captialism, it is crucial to build an organization that educates the working class in their defense-both against the political propaganda of the ruling class and against any physical threats they may encounter.

This document serves to outline the mission, goals, and organizational structure of the People's Liberation Training Committee (PLT-COM).

== Mission

PLT-COM's mission is to provide firearms training, political education, and community organization to the working class.

We do not see firearms as a vehicle to pursue political change, but as an important tool for communities' self defense while pursuing liberatory change in their lives.

== Organizational structure
=== National Structure
* <<Committee-Process.adoc#,Central Committee>>
* National Committees
* National Working Groups

=== Local Structure
* Regions

=== Chapter Structure
* Chapter Central Committee
* Chapter Committees
* Chapter Working-Groups

== Processes and Documents
* New Members
* New Chapter Formation
* Joining an Existing Chapter
* Membership Levels
* Budget Requests
* Action Requests
* Committee Reports
