= Member Expectations
:toc:

To effectively accomplish our goals as an organization, PLT-COM requires dedication and discipline from its members. A member's participation in the work is the difference between a revolutionary organization that makes changes in their community and a social organization that does nothing of importance. Outlined below are base expectations for members. These expectations are the bare minimum to maintain membership.

== Probationary Policy

Should a member fail to meet the expectations set below, they will be placed on probationary status. A meeting will be held with the Regional Director and Chapter Director to discuss what issues the member may be having that prevents their full participation. The RD and CD will sumbit a joint report to the CC with their recommended course of action. The CC will review the report, make any adjustments needed, and send the final decision back to the CD, RD, and member to be implemented.

The goal of the probationary policy is not to be punative, but rather to dissect the issues that may be going on and attempt to correct them. However, members failing to meet the 
guidelines set forth in the probationary report may be removed from the organization.


== Grounds for Removal

Certain violations of the member expecations policy warrant immediate removal from the organization. Those include:

* sexual assault
* sexual harrassment
* bigotry
* discrimination on the basis of gender, race, or sexual orientation
* violence towards another member


Other violations of the member expectations policy will be addressed using the probationary policy. Should a member fail to mee the guidelines set in the probationary report, the member, CD, and RD will come before the Central Committee to discuss the situation. The Central Committee will then decide whether to remove the member, or to continue with another probationary report. Should a member fail to meet the conditions of the second probationary report, they are removed from the organization.

== New Member Requirements

New members are held to the same expectations as full members, except for committeee or working group requirements, and instead must meet the education requirements listed below to become full members.

=== Education Requirements

==== Political Education

New members must pass PLTCOMs introduction to socialism and Marxism. This can be waived if a member has joined a party who provides a political education program. 

==== Firearms Education

New members must demonstrate a proficency with firearms, passing the introduction to firearms course provided by PLTCOM

==== First Aid Education

New members must pass the introduction to first aid course provided by PLTCOM

== Full Member Requirements  


=== Attendance Requirement


==== Chapter Meetings

At a minimum, chapters should be holding 1 quarterly general meeting. Members need to attend 75% of general meetings held during a year. 

==== Committee or Working Group meetings

Committee or Working Group meetings should be held monthly, at a minimum. Members need to attend 75% of committee or working group meetings held during a year.

=== Workload Requirement

Full members are required to join one committee or working group and participate fully in the work being done. 


=== Party requirement

All members must join a party within 6 months of joining PLTCOM, or have documented progress towards joining, or provide evidence there is no suitible party in their area.


   