= Member Expectations
:toc:

To effectively accomplish our goals as an organization, PLTCOM requires dedication and discipline from its members. A member's participation in the work is the difference between a revolutionary organization that makes changes in their community and a social organization that does nothing of importance. Outlined below are base expectations for members. These expectations are the bare minimum to maintain membership.

== Probationary Policy

Should a member fail to meet the expectations set below, they will be placed on probationary status. A meeting will be held with the Committee Director to discuss what issues the member may be having that prevents their full participation. The Committee Director will submit a report to the Central Committee with their recommended course of action. The Central Committee will review the report, make any adjustments needed, and send the final decision back to the Committee Director and member to be implemented.

The goal of the probationary policy is not to be punitive, but rather to dissect the issues that may be going on and attempt to correct them. However, members failing to meet the
guidelines set forth in the probationary report may be removed from the organization.


== Grounds for Removal

Certain violations of the member expectations policy warrant immediate removal from the organization. Those include:

* sexual assault
* sexual harassment
* bigotry
* discrimination on the basis of gender, race, or sexual orientation
* violence towards another member
* association with right wing or fascist groups


Other violations of the member expectations policy will be addressed using the probationary policy. Should a member fail to meet the guidelines set in the probationary report, the member and Committee Director, will come before the Central Committee to discuss the situation. The Central Committee will then decide whether to remove the member, or to continue with another probationary report. Should a member fail to meet the conditions of the second probationary report, they are removed from the organization.


== Membership Tiers

=== Provisional

Provisional members have freshly joined the organization. They cannot vote. To move from Provisional to Voting, a member must participate in ED101: Introduction to Scientific Socialism. The requirement can be waived through participation in a Party with an equivalent education component, or at the discretion of the Central Committee.

=== Voting

Voting members have completed the political education requirement to participate in PLTCOM activities, and are expected to join at least one, but not more than two total, working groups or committees. For more information on working groups and committees, <<Committees-splashpage.adoc#,click here.>>

Voting members are ineligible to hold leadership positions, and must complete the full member requirements to become a full membership to hold office.

=== Full Member

To become a full member, a voting member must join a Marxist-Leninist or Marxist-Leninist-Maoist party, or show proof that progress has been made towards joining a party, or proof that no party exists in the area. Full members can hold leadership positions in the organization.


== Full Member Requirements

=== Committee or Working Group meetings

Committee or Working Group meetings should be held monthly, at a minimum. Members need to attend 75% of committee or working group meetings held during a year to remain a full member. If this is not met, member status will revert to probationary status.

=== Workload Requirement


Full members are required to join one committee or working group and participate fully in the work being done.


=== Party requirement

All members must join a party within 6 months of joining PLTCOM, or have documented progress towards joining, or provide evidence there is no suitable party in their area.

== On Inter-Organizational Discourse

=== Experience Thus Far

In the course of our development, it has been an ideological struggle between the interests of socialist construction, and those that do not share this interest. As a result, the rise of antagonism to the science to socialism has resulted in the liberal rejection of ideological struggle. As most popular "socialist" organizations are not structured according to democratic centralism, nor are they actually oriented toward revolution, they not only allow, but actively promote a philistine perspective.

"Socialist" in the sparsely politically conscious moment can mean anyone from a Sanders supporter to Stalin. Even anarchists try and consider themselves "socialist." What a socialist actually is, which Marx and Lenin definitively put on a scientific basis, is that person who supports the interest of scientific socialist construction. If someone does not explicitly give support to scientific socialist construction then there is little reason to believe that they actually do have such an interest.

When dealing with comrades who do have such an interest, but there is a disagreement keep this in mind: Do your words help unite or divide those with the interests of scientific socialist construction? You must always come from the perspective of unity, and only at this point, once such explicit unity has been made known, can criticism begin to distinguish between what is right and what is wrong, where the wrong is fully acknowledged as a mistake, and a unity on a new basis is established.

=== Combating Liberalism

The manifestation of antagonistic contradictions within the organization is a serious threat. What is considered otherwise normal social behavior elsewhere under capitalism can lead to disastrous consequences. Potentially throwing the whole organization into a crisis beyond saving. This is why any issue that a comrade has must absolutely be brought up at any point which should have the utmost serious focus. The process of "Unity-Criticism-Unity" outlined above is how we deal with this, but to avoid voicing concerns will only lead to a deepening of tension, the transformation of a non-antagonistic contradiction into antagonistic.

To avoid confrontation over incorrect views is tantamount to a criticism of scientific socialism because the ideological struggle has been rejected, and philistine views are allowed to continue festering into an inevitable antagonistic contradiction. There is an acknowledgment of a mistake but no course of correction. Without a correction how can these views change? Do they just change magically on their own? No, they are changed by an external force.

Therefore it is **mandatory** that in the course of organizational work that _full members_ serve as mentors for the _new members_ and vigilantly stand guard against a liberal apathy for ideological struggle and appropriately correct comrades that display incorrect ideas. What is correct and incorrect is generally learned by two methods: social practice, and scientific experiment. The ideas that succeed are those that are right and the ideas that fail are incorrect. A simplistic but accurate consideration to any context. Where to succeed is desirable and failure is not in relation to our social practice.

Scientific socialism is not an abstract dogma, its is consciously maintained to coincide with existing reality. It evolves dialectically to reflect the objective conditions of its environment. So too, must we work to correct our ideas to reflect a world in motion.


Full members are required to join one committee or working group and participate fully in the work being done.
