= Member Expectations
:toc:

To effectively accomplish our goals as an organization, PLT-COM requires dedication and discipline from its members. A member's participation in the work is the difference between a revolutionary organization that makes changes in their community and a social organization that does nothing of importance. Outlined below are base expectations for members. These expectations are the bare minimum to maintain membership.

== Probationary Policy

Should a member fail to meet the expectations set below, they will be placed on probationary status. A meeting will be held with the Regional Director and Chapter Director to discuss what issues the member may be having that prevents their full participation. The RD and CD will submit a joint report to the CC with their recommended course of action. The CC will review the report, make any adjustments needed, and send the final decision back to the CD, RD, and member to be implemented.

The goal of the probationary policy is not to be punitive, but rather to dissect the issues that may be going on and attempt to correct them. However, members failing to meet the
guidelines set forth in the probationary report may be removed from the organization.


== Grounds for Removal

Certain violations of the member expectations policy warrant immediate removal from the organization. Those include:

* sexual assault
* sexual harassment
* bigotry
* discrimination on the basis of gender, race, or sexual orientation
* violence towards another member
* association with right wing or fascist groups


Other violations of the member expectations policy will be addressed using the probationary policy. Should a member fail to mee the guidelines set in the probationary report, the member, CD, and RD will come before the Central Committee to discuss the situation. The Central Committee will then decide whether to remove the member, or to continue with another probationary report. Should a member fail to meet the conditions of the second probationary report, they are removed from the organization.


== Membership Tiers

=== Provisional

Provisional members have freshly joined the organization. They cannot vote. To move from Provisional to Voting, a member must participate in the PLTCOM introduction to Socialism and Marxism socialism. The requirement can be waived through participation in a Party with an equivalent education component, or at the discretion of the Central Committee.

=== Voting

Voting members have completed the political education requirement to participate in PLTCOM activities, and are expected to join at least one, but not more than two total, working groups or committees. For more information on working groups and committees, <<Committees-splashpage.adoc#,click here.>> Voting members are expected to pass the introduction to firearms and introduction to first aid courses. 

Voting members are ineligible to hold leadership positions, and must complete the requirements to become a full membership to hold office.

=== Full Member

To become a full member, a voting member must join a Marxist-Leninist or Marxist-Leninist-Maoist party, or show proof that progress has been made towards joining a party, or proof that no party exists in the area. Full members can hold leadership positions in the organization.

== Attendance Requirements


==== Chapter Meetings

At a minimum, chapters should be holding 1 quarterly general meeting. Members need to attend 75% of general meetings held during a year.

==== Committee or Working Group meetings

Committee or Working Group meetings should be held monthly, at a minimum. Members need to attend 75% of committee or working group meetings held during a year.

=== Workload Requirement

Full members are required to join one committee or working group and participate fully in the work being done.
