= Organizational Structure

PLT-COM is organized via Democratic Centralism. This method fuses the traditional debate and discussion of democracy, with the discipline of centralism. In other words, democratic centralism is "Freedom in discussion and unity in action".

For example, Local PLT-COM chapters see the need for a food distribution network at the ground level. Chapters submit Ground Report Forms (GRFs) detailing their observations and needs.The central committee starts an information gathering period. Chapters pass information and ideas up the chain to the central committee. The central committee gathers all available data, formulates a plan, then enters a debate period. During the debate period, chapters will deliberate the contents of the plan and return either a decision or changes to the plan. Once the debate period has closed, the central committee then implements the plan for a food distribution network. Changes to the food distribution network are not made once a decision has been reached, unless there is something that is obviously not functioning properly, which can be brought to the attention of the central committee in the same fashion the problem of food distribution was originally brought up.

== National structure

=== Central Committee

The Central Committee (CC) of PLT-COM is composed of a number of members that serve various administrative functions to keep the organization running and on task.
The members of the central committee are:

* President
* Vice President
* Treasurer
* Director of Chapter Organizing (DCO)
* National Firearms Director (NFD)
* National Political Education Director (NPED)
* National First Aid Director (NFAD)

Members of the Central Committee serve 1 year terms, with no term limits. New candidates for the postions on the Central Committee are nominated from their analogous position or committee directly below them. The entirety membership gets to vote on the nominee This means:

* President, VP, Treasurer and the DCO are chosen from existing Regional Directors (RDs)
* The NFD is chosen from the Chapter Firearms Directors (CFD)
* The NPED is chosen from the Chapter Political Education Directors (CPEDs)
* The NFAD is chosen from the Chapter First Aid Director (CFADs)

This ensures that the people on the CC have relevant experience at a smaller level before stepping into roles on the national level.

The Central Committee meets on a ____ basis to decide on issues that are crucial to the function of the organization. Members can submit issues to be considered by the Central Committee by sending the Ground Report Form (GRF) to their RD.

To see the requirements to sit on the Central Committee, click on the name of each position.

=== National Committees
==== National Firearms Education Committee (NFEC)

The NFEC sets the guidelines for firearms education throughout the organization. It is composed of the Chapter Firearms Directors (CFDs) from all chapters, and is lead by the National Firearms Director (NFD). The NFEC meets on a ___ basis to assess the progress of chapters in implementing their firearms programs, best practices for doing so, and new ideas for programs. To submit and idea to the NFEC, fill out a Project Proposal Form (PPF) and send it to your CFD.

==== National Political Education Committee (NPEC)
==== National First Aid Committee (NFAC)


=== National Working Groups
== Regional Structure
=== Regional Directors
=== Regional Council


== Chapter Structure

==== Chapter Committees
==== Chapter Working Groups
