= Elections

It is extremely important that members participate in the selection of their leadership. However, direct election of leadership can quickly turn into a popularity contest, which should be avoided. To balance these two requirements, the election procedure below has been implemented.

== Chapter level leadership

=== Chapter Central Committee (other than committee heads)

The chapter members will nominate other members for the positions of Chapter Director, Assistant Chapter Director, Chapter Secretary, and Chapter Treasurer.

A nominating committee, composed of the current Chapter Central Committee (if available), the <<RDC.adoc#, Regional Director's Council (RDC)>>, and the <<Central Committee.adoc#,National Central Committee>>, will review the nominations, conduct interviews, and vote on the most qualified candidate. The candiate winning a majority of votes from the nominating committee will be chosen as the winner.

=== Chapter Committee Director

Any person pursuing nomination for committee directorship must sumbit an application. 

The chapter members will nominate 1-3 other members to lead Chapter Committes after reviewing the sumbitted directorship application. 

A nominating committee, composed of the Chapter Central Committee, the <<RD.adoc#,Regional Director (RD)>> and <<NFED.adoc#,National Firearms Education Director (NFED)>>, will review the nominations, conduct interviews and vote on the most qualified candidate. The candiate winning a majority of votes from the nominating committee will be chosen as the winner.

== Regional Leadership

=== Regional Directors (RDs)

Regional directors are chosen from chapter directors. Chapter directors may nominate other chapter directors for the RD position.

A nominating committee composed of the Regional Council, Chapter Directors, and the National Central Committee will review the nominations, conduct interviews, and vote on the most qualified candidate. The candiate winning a majority of votes from the nominating committee will be chosen as the winner.

== National Leadership

=== General Secretary and Undersecretary

National President and Vice President will be selected by all members eligible to vote from RDs who wish to run.

A candidate's forum, with each candidate presenting their plans and ideas for the organization, will be held 1 month prior to the date of the election. The general membership will have 1 month to deliberate their ideas. The candidates should make themselves available for questions and critiques.

Voting will be done by ranked-choice, with the candidate the majority of members select as their top choice becoming the General Secretary, and the majority's second choice becoming the Undersecretary.

=== Finance Secretary and Recording Secretary

The Finance Secretary and Recording Secretary positions will be selected from members who submit their applications to the Central Committee
